package net.posdaca.oiia.project

import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption
import java.util.Locale

data class HoI4ModSettings(
    val name: String,
    val modVersion: String,
    val supportedVersion: String,
    val tags: List<String>,
    val authors: List<String>,
    val projectDirectory: Path,
    val modDirectory: Path,
    val launcherDescriptorDirectory: Path?,
)

object HoI4ModTemplateGenerator {
    const val MAX_TAG_COUNT = 10

    val availableTags = listOf(
        "Alternative History",
        "Balance",
        "Events",
        "Fixes",
        "Gameplay",
        "Graphics",
        "Historical",
        "Ideologies",
        "Map",
        "Military",
        "National Focuses",
        "Sound",
        "Technologies",
        "Translation",
        "Utilities",
    )

    fun defaultModRoot(): Path {
        val userHome = Path.of(System.getProperty("user.home"))
        return userHome.resolve("Documents")
            .resolve("Paradox Interactive")
            .resolve("Hearts of Iron IV")
            .resolve("mod")
    }

    fun sanitizeModId(value: String): String {
        val normalized = value.trim()
            .lowercase(Locale.ROOT)
            .replace(Regex("[^a-z0-9._-]+"), "_")
            .replace(Regex("_+"), "_")
            .trim('_', '.', '-')
        return normalized.ifBlank { "hoi4_mod" }
    }

    fun parseList(value: String): List<String> {
        return value.split(',', ';')
            .map { it.trim() }
            .filter { it.isNotEmpty() }
            .distinct()
    }

    fun generate(settings: HoI4ModSettings): List<Path> {
        val projectDirectory = settings.projectDirectory.normalize()
        val modDirectory = settings.modDirectory.normalize()
        Files.createDirectories(projectDirectory)
        Files.createDirectories(modDirectory)

        val descriptor = descriptorContent(settings, includePath = false)
        val descriptorFile = modDirectory.resolve("descriptor.mod")
        writeText(descriptorFile, descriptor)

        val readmeFile = projectDirectory.resolve("README.md")
        writeText(readmeFile, readmeContent(settings))

        val gitignoreFile = projectDirectory.resolve(".gitignore")
        writeText(gitignoreFile, gitignoreContent())

        val createdFiles = mutableListOf(descriptorFile, readmeFile, gitignoreFile)
        val launcherDescriptorDirectory = settings.launcherDescriptorDirectory
        if (launcherDescriptorDirectory != null) {
            Files.createDirectories(launcherDescriptorDirectory)
            val descriptorName = sanitizeModId(settings.name) + ".mod"
            val launcherDescriptor = launcherDescriptorDirectory.resolve(descriptorName)
            writeText(launcherDescriptor, descriptorContent(settings, includePath = true))
            createdFiles.add(launcherDescriptor)
        }

        return createdFiles
    }

    fun descriptorContent(settings: HoI4ModSettings, includePath: Boolean): String {
        return buildString {
            appendKeyValue("name", settings.name)
            if (includePath) appendKeyValue("path", settings.modDirectory.normalize().toString().replace('\\', '/'))
            appendKeyValue("version", settings.modVersion)
            appendTags(settings.tags.take(MAX_TAG_COUNT))
            appendKeyValue("supported_version", settings.supportedVersion)
        }
    }

    private fun StringBuilder.appendKeyValue(key: String, value: String) {
        val escaped = value.replace("\\", "\\\\").replace("\"", "\\\"")
        append(key).append("=\"").append(escaped).append('"').append('\n')
    }

    private fun StringBuilder.appendTags(tags: List<String>) {
        append("tags={").append('\n')
        tags.forEach { tag ->
            append('\t').append('"')
                .append(tag.replace("\\", "\\\\").replace("\"", "\\\""))
                .append('"')
                .append('\n')
        }
        append('}').append('\n')
    }

    private fun readmeContent(settings: HoI4ModSettings): String {
        return """
            |# ${settings.name}
            |
            |Hearts of Iron IV mod.
            |
            |- Mod version: ${settings.modVersion}
            |- Supported HOI4 version: ${settings.supportedVersion}
            |- Tags: ${settings.tags.take(MAX_TAG_COUNT).joinToString(", ").ifBlank { "None" }}
            |- Authors: ${settings.authors.joinToString(", ").ifBlank { "None" }}
            |- Mod content: src
            |
            |This project was generated by Oiia.
            |
        """.trimMargin()
    }

    private fun gitignoreContent(): String {
        return """
            |.idea/
            |*.iml
            |*.zip
            |*.log
            |
        """.trimMargin()
    }

    private fun writeText(file: Path, content: String) {
        Files.createDirectories(file.parent)
        Files.writeString(
            file,
            content,
            StandardCharsets.UTF_8,
            StandardOpenOption.CREATE,
            StandardOpenOption.TRUNCATE_EXISTING,
            StandardOpenOption.WRITE,
        )
    }
}
